import type { Part } from "./types"

type PinDefinition = readonly [number: string, label: string, electricalType: string]
type Device = Pick<Part,"value"|"footprint"|"mpn"|"lcsc"|"datasheet"> & { pins: readonly PinDefinition[] }

/** Shared electrical/package definitions; supplier selections are intentionally pinned. */
export const devices = {
  C_0402_1uF_16V: {
    value: "1uF 16V",
    footprint: "Capacitor_SMD:C_0402_1005Metric",
    mpn: "",
    lcsc: "C52923",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_0402_100nF_10V: {
    value: "100nF 10V",
    footprint: "Capacitor_SMD:C_0402_1005Metric",
    mpn: "",
    lcsc: "C1525",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_0402_10nF_10V: {
    value: "10nF 10V",
    footprint: "Capacitor_SMD:C_0402_1005Metric",
    mpn: "",
    lcsc: "C15195",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_0603_4_7uF_16V: {
    value: "4.7uF 16V",
    footprint: "Capacitor_SMD:C_0603_1608Metric",
    mpn: "",
    lcsc: "C19666",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_0603_10uF: {
    value: "10uF",
    footprint: "Capacitor_SMD:C_0603_1608Metric",
    mpn: "",
    lcsc: "C19702",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_0603_0_1uF: {
    value: "0.1uF",
    footprint: "Capacitor_SMD:C_0603_1608Metric",
    mpn: "",
    lcsc: "C14663",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_1206_0_1uF: {
    value: "0.1uF",
    footprint: "Capacitor_SMD:C_1206_3216Metric",
    mpn: "GRM31C5C2A104JA01L",
    lcsc: "C405303",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_0805_10uF_16V: {
    value: "10uF 16V",
    footprint: "Capacitor_SMD:C_0805_2012Metric",
    mpn: "",
    lcsc: "C15850",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  C_0603_22pF_50V: {
    value: "22pF 50V",
    footprint: "Capacitor_SMD:C_0603_1608Metric",
    mpn: "",
    lcsc: "C1653",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  LED: {
    value: "LED",
    footprint: "LED_SMD:LED_0603_1608Metric",
    mpn: "",
    lcsc: "C2286",
    datasheet: "",
    pins: [["1","K","passive"],["2","A","passive"]],
  },
  B5819W: {
    value: "B5819W",
    footprint: "Diode_SMD:D_SOD-123",
    mpn: "",
    lcsc: "C8598",
    datasheet: "",
    pins: [["1","K","passive"],["2","A","passive"]],
  },
  LESD8D3_3CAT5G: {
    value: "LESD8D3.3CAT5G",
    footprint: "Diode_SMD:D_SOD-882",
    mpn: "",
    lcsc: "C172409",
    datasheet: "",
    pins: [["1","A1","passive"],["2","A2","passive"]],
  },
  WS2812B_V6: {
    value: "WS2812B",
    footprint: "LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm",
    mpn: "WS2812B-V6",
    lcsc: "C52917433",
    datasheet: "https://www.lcsc.com/datasheet/C52917433.pdf",
    pins: [
      ["1","VDD","power_in"],
      ["2","DOUT","output"],
      ["3","VSS","power_in"],
      ["4","DIN","input"],
    ],
  },
  LESD5D5_0CT1G: {
    value: "LESD5D5.0CT1G",
    footprint: "Diode_SMD:D_SOD-523",
    mpn: "",
    lcsc: "C2982332",
    datasheet: "",
    pins: [["1","A1","passive"],["2","A2","passive"]],
  },
  USB4105_GF_A: {
    value: "USB4105-GF-A",
    footprint: "Crimpdeq:GCT_USB4105-GF-A",
    mpn: "USB4105-GF-A",
    lcsc: "C165948",
    datasheet: "https://gct.co/files/drawings/usb4105.pdf",
    pins: [
      ["A1_B12","GND","power_in"],
      ["A4_B9","VBUS","power_in"],
      ["A5","CC1","bidirectional"],
      ["A6","DP1","bidirectional"],
      ["A7","DN1","bidirectional"],
      ["A8","SBU1","bidirectional"],
      ["B1_A12","GND","power_in"],
      ["B4_A9","VBUS","power_in"],
      ["B5","CC2","bidirectional"],
      ["B6","DP2","bidirectional"],
      ["B7","DN2","bidirectional"],
      ["B8","SBU2","bidirectional"],
      ["S1","SHELL_GND","power_in"],
      ["S2","SHELL_GND","power_in"],
      ["S3","SHELL_GND","power_in"],
      ["S4","SHELL_GND","power_in"],
    ],
  },
  PAD_B_MINUS: {
    value: "B-_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  PAD_SW_PLUS: {
    value: "SW+_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  PAD_B_PLUS: {
    value: "B+_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  PAD_SW_MINUS: {
    value: "SW-_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  PAD_A_PLUS: {
    value: "A+_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  PAD_A_MINUS: {
    value: "A-_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  PAD_E_PLUS: {
    value: "E+_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  PAD_E_MINUS: {
    value: "E-_Cable_Pad",
    footprint: "TestPoint:TestPoint_THTPad_D1.5mm_Drill0.7mm",
    mpn: "",
    lcsc: "",
    datasheet: "",
    pins: [["1","Pin_1","passive"]],
  },
  SPH4018H2R2MT_2_2uH_2_2A: {
    value: "SPH4018H2R2MT (2.2uH 2.2A)",
    footprint: "Inductor_SMD:L_Bourns-SRN4018",
    mpn: "",
    lcsc: "C370436",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  DMG3415U_7: {
    value: "DMG3415U",
    footprint: "Crimpdeq:SOT-23",
    mpn: "DMG3415U-7",
    lcsc: "C96616",
    datasheet: "https://www.diodes.com/assets/Datasheets/DMG3415U.pdf",
    pins: [
      ["1","G","input"],
      ["2","S","passive"],
      ["3","D","passive"],
    ],
  },
  R_0402_10kR_1: {
    value: "10kR 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "",
    lcsc: "C60490",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  R_0402_1kR_1: {
    value: "1kR 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "",
    lcsc: "C11702",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  R_0402_100R_1: {
    value: "100R 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "",
    lcsc: "C25076",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  R_0402_100kR_1: {
    value: "100kR 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "",
    lcsc: "C25741",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  R_0402_0R_1: {
    value: "0R 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "",
    lcsc: "C17168",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  R_0402_22k1R_1: {
    value: "22k1R 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "",
    lcsc: "C43473",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  R_0402_5k1R_1: {
    value: "5k1R 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "",
    lcsc: "C25905",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  R_0402_47R_1: {
    value: "47R 1%",
    footprint: "Resistor_SMD:R_0402_1005Metric",
    mpn: "0402WGF470JTCE",
    lcsc: "C25118",
    datasheet: "",
    pins: [["1","","passive"],["2","","passive"]],
  },
  ESP32_C3_MINI_1: {
    value: "ESP32-C3-MINI-1",
    footprint: "Crimpdeq:ESP32-C3-MINI-1",
    mpn: "ESP32-C3-MINI-1",
    lcsc: "C2838502",
    datasheet: "https://www.espressif.com/sites/default/files/documentation/esp32-c3-mini-1_datasheet_en.pdf",
    pins: [
      ["1","GND","power_in"],
      ["2","GND","power_in"],
      ["3","3V3","power_in"],
      ["4","NC","no_connect"],
      ["5","GPIO2/ADC1_CH2","bidirectional"],
      ["6","GPIO3/ADC1_CH3","bidirectional"],
      ["7","NC","no_connect"],
      ["8","EN/CHIP_PU","input"],
      ["9","NC","no_connect"],
      ["10","NC","no_connect"],
      ["11","GND","power_in"],
      ["12","GPIO0/ADC1_CH0/XTAL_32K_P","bidirectional"],
      ["13","GPIO1/ADC1_CH1/XTAL_32K_N","bidirectional"],
      ["14","GND","power_in"],
      ["15","NC","no_connect"],
      ["16","GPIO10","bidirectional"],
      ["17","NC","no_connect"],
      ["18","GPIO4/ADC1_CH4","bidirectional"],
      ["19","GPIO5/ADC2_CH0","bidirectional"],
      ["20","GPIO6","bidirectional"],
      ["21","GPIO7","bidirectional"],
      ["22","GPIO8","bidirectional"],
      ["23","GPIO9","bidirectional"],
      ["24","NC","no_connect"],
      ["25","NC","no_connect"],
      ["26","GPIO18/USB_D-","bidirectional"],
      ["27","GPIO19/USB_D+","bidirectional"],
      ["28","NC","no_connect"],
      ["29","NC","no_connect"],
      ["30","GPIO20/U0RXD","bidirectional"],
      ["31","GPIO21/U0TXD","bidirectional"],
      ["32","NC","no_connect"],
      ["33","NC","no_connect"],
      ["34","NC","no_connect"],
      ["35","NC","no_connect"],
      ["36","GND","power_in"],
      ["37","GND","power_in"],
      ["38","GND","power_in"],
      ["39","GND","power_in"],
      ["40","GND","power_in"],
      ["41","GND","power_in"],
      ["42","GND","power_in"],
      ["43","GND","power_in"],
      ["44","GND","power_in"],
      ["45","GND","power_in"],
      ["46","GND","power_in"],
      ["47","GND","power_in"],
      ["48","GND","power_in"],
      ["49","GND","power_in"],
      ["50","GND","power_in"],
      ["51","GND","power_in"],
      ["52","GND","power_in"],
      ["53","GND","power_in"],
    ],
  },
  MCP73831T_2ACI_OT: {
    value: "MCP73831T-2ACI/OT",
    footprint: "Crimpdeq:MCP73831_SOT-23-5",
    mpn: "",
    lcsc: "C424093",
    datasheet: "http://ww1.microchip.com/downloads/en/DeviceDoc/20001984g.pdf",
    pins: [
      ["1","STAT","output"],
      ["2","VSS","power_in"],
      ["3","VBAT","power_out"],
      ["4","VDD","power_in"],
      ["5","PROG","input"],
    ],
  },
  ADS1220IPWR: {
    value: "ADS1220",
    footprint: "Package_SO:TSSOP-16_4.4x5mm_P0.65mm",
    mpn: "ADS1220IPWR",
    lcsc: "C48263",
    datasheet: "https://www.ti.com/lit/ds/symlink/ads1220.pdf",
    pins: [
      ["1","SCLK","input"],
      ["2","~{CS}","input"],
      ["3","CLK","input"],
      ["4","DGND","power_in"],
      ["5","AVSS","power_in"],
      ["6","AIN3/REFN1","input"],
      ["7","AIN2","input"],
      ["8","REFN0","input"],
      ["9","REFP0","input"],
      ["10","AIN1","input"],
      ["11","AIN0/REFP1","input"],
      ["12","AVDD","power_in"],
      ["13","DVDD","power_in"],
      ["14","~{DRDY}","output"],
      ["15","DOUT/~{DRDY}","output"],
      ["16","DIN","input"],
    ],
  },
  MAX17048G_T10: {
    value: "MAX17048G+T10",
    footprint: "Package_DFN_QFN:TDFN-8-1EP_2x2mm_P0.5mm_EP0.8x1.2mm",
    mpn: "MAX17048G+T10",
    lcsc: "C2682616",
    datasheet: "https://www.analog.com/media/en/technical-documentation/data-sheets/MAX17048-MAX17049.pdf",
    pins: [
      ["1","GND","power_in"],
      ["2","CELL","power_in"],
      ["3","VDD","power_in"],
      ["4","GND","power_in"],
      ["5","~{ALRT}","open_collector"],
      ["6","QSTRT","input"],
      ["7","SCL","input"],
      ["8","SDA","bidirectional"],
      ["9","GND","power_in"],
    ],
  },
  SY8088: {
    value: "SY8088",
    footprint: "Crimpdeq:SY8088_SOT-23-5",
    mpn: "",
    lcsc: "C479072",
    datasheet: "",
    pins: [
      ["1","EN","input"],
      ["2","GND","power_in"],
      ["3","LX","power_out"],
      ["4","IN","power_in"],
      ["5","FB","input"],
    ],
  },
} satisfies Record<string,Device>
